name: Java CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: burp_nu_te_gen_Releases.zip
          path: target/*.jar
